#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 16 17:55:32 2019

@author: eric
"""

result = 0
num = 0

while num < 1000:
    if num%3 ==0 or num%5 == 0:
        result = result + num
        num = num + 1
    else:
        num = num + 1
        
print (result)
    